name: Publish k3s image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docker/**
      - .github/workflows/publish-image.yaml

jobs:
  publish-k3s-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["v1.29.8-k3s1", "v1.30.4-k3s1", "v1.31.0-k3s1"]
        cuda_version: ["12.4.1-base-ubuntu22.04"]

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: docker/setup-buildx-action@8026d2bc3645ea78b0d2544766a1225eb5691f89 # v3.7.0

      - name: Setup UDS
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/setup@e3008473beab00b12a94f9fcc7340124338d5c08 # v0.13.1
        with:
          registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the CUDA K3s image
        run: |
          uds run publish-image \
            --set VERSION=${{matrix.version}} \
            --set CUDA_VERSION=${{matrix.version}} \
            --no-progress

      - name: Publish the CUDA K3s image
        run: |
          uds run publish-image \
            --set VERSION=${{matrix.version}} \
            --set CUDA_VERSION=${{matrix.version}} \
            --no-progress
